import { ProductPreview } from "./IProduct";

export const products: ProductPreview[] = [
    {
      productId: 1,
      name: "UltraGamer Pro",
      price: 1999.99,
      rating: 4.8,
      image: "/placeholder.svg?height=150&width=150",
      specs: "RTX 3080, 32GB RAM",
      category: "Desktop PC",
      inStock: true,
      discount: 10,
      isNew: true,
      colors: [],
      description: "A powerful gaming PC with the latest NVIDIA graphics card and a large amount of RAM.",
      features: ["RTX 3080", "32GB RAM", "1TB SSD"],
      brand: ["PC R5"]
    },
    {
      productId: 2,
      name: "EpicBattle Station",
      price: 2499.99,
      rating: 4.9,
      image: "/placeholder.svg?height=150&width=150",
      specs: "RTX 3090, 64GB RAM",
      category: "Desktop PC",
      inStock: true,
      discount: 10,
      isNew: false,
      colors: [],
      description: "A high-performance gaming PC with the latest NVIDIA graphics card and a large amount of RAM.",
      features: ["RTX 3090", "64GB RAM", "2TB SSD"],
      brand: ["PC I3"],
    },
    {
      productId: 3,
      name: "UltraGamer Pro",
      price: 1999.99,
      rating: 4.8,
      image: "/placeholder.svg?height=150&width=150",
      specs: "RTX 3080, 32GB RAM",
      category: "Desktop PC",
      inStock: true,
      discount: 10,
      isNew: true,
      colors: [],
      description: "A powerful gaming PC with the latest NVIDIA graphics card and a large amount of RAM.",
      features: ["RTX 3080", "32GB RAM", "1TB SSD"],
      brand: ["PC I5"],
    },
    {
      productId: 4,
      name: "UltraGamer Pro",
      price: 1999.99,
      rating: 4.8,
      image: "/placeholder.svg?height=150&width=150",
      specs: "RTX 3080, 32GB RAM",
      category: "Desktop PC",
      inStock: true,
      discount: 10,
      isNew: true,
      colors: [],
      description: "A powerful gaming PC with the latest NVIDIA graphics card and a large amount of RAM.",
      features: ["RTX 3080", "32GB RAM", "1TB SSD"],
      brand: ["PC I7"],
    },
    {
      productId: 5,
      name: "EpicBattle Station",
      price: 2499.99,
      rating: 4.9,
      image: "/placeholder.svg?height=150&width=150",
      specs: "RTX 3090, 64GB RAM",
      category: "Desktop PC",
      inStock: true,
      discount: 10,
      isNew: false,
      colors: [],
      description: "A high-performance gaming PC with the latest NVIDIA graphics card and a large amount of RAM.",
      features: ["RTX 3090", "64GB RAM", "2TB SSD"],
      brand: ["PC I9"],
    },
    {
      productId: 6,
      name: "UltraGamer Pro",
      price: 1999.99,
      rating: 4.8,
      image: "/placeholder.svg?height=150&width=150",
      specs: "RTX 3080, 32GB RAM",
      category: "Desktop PC",
      inStock: true,
      discount: 10,
      isNew: true,
      colors: [],
      description: "A powerful gaming PC with the latest NVIDIA graphics card and a large amount of RAM.",
      features: ["RTX 3080", "32GB RAM", "1TB SSD"],
      brand: ["PC R3"],
    },
    
    {
      productId: 7,
      name: "UltraGamer Pro",
      price: 1999.99,
      rating: 4.8,
      image: "/placeholder.svg?height=150&width=150",
      specs: "RTX 3080, 32GB RAM",
      category: "Desktop PC",
      inStock: true,
      discount: 10,
      isNew: true,
      colors: [],
      description: "A powerful gaming PC with the latest NVIDIA graphics card and a large amount of RAM.",
      features: ["RTX 3080", "32GB RAM", "1TB SSD"],
      brand: ["PC R9"],
    },
    {
      productId: 8,
      name: "UltraGamer Pro",
      price: 1999.99,
      rating: 4.8,
      image: "/placeholder.svg?height=150&width=150",
      specs: "RTX 3080, 32GB RAM",
      category: "Desktop PC",
      inStock: true,
      discount: 10,
      isNew: true,
      colors: [],
      description: "A powerful gaming PC with the latest NVIDIA graphics card and a large amount of RAM.",
      features: ["RTX 3080", "32GB RAM", "1TB SSD"],
      brand: ["PC I5"],
    },
  
  ];